openapi: 3.0.0
info:
  title: Greeting Service API
  version: 1.0.0
paths:
  /greeting:
    get:
      summary: Retrieves a greeting message
      responses:
        '200':
          description: A greeting message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
