apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: Greeting Service
      port: 9090
      type: REST
      networkVisibility: Project
      context: /greeting
      schemaFilePath: greeting_openapi.yaml
  outbound:
    serviceReferences: []
